/**
 * Internal lyrics format for Piano Maestro.
 *
 * A lyrics file is a JSON object with this shape:
 *
 * {
 *   "title": "optional song title",
 *   "lyrics": [
 *     { "time": 0.0,  "text": "Hel-" },
 *     { "time": 0.5,  "text": "lo " },
 *     { "time": 1.2,  "text": "World" },
 *     ...
 *   ]
 * }
 *
 * Each entry associates a timestamp (seconds from start) with a text fragment
 * (syllable, word, or phrase). The LyricsPanel displays the fragment whose
 * `time` is the largest value ≤ currentTime.
 *
 * This format is intentionally minimal so it can be generated by hand or by
 * a future backend endpoint that auto-aligns lyrics to a MIDI file.
 */

/**
 * @typedef {{ time: number, text: string }} LyricEntry
 * @typedef {{ title?: string, lyrics: LyricEntry[] }} LyricsFile
 */

/**
 * Validate and parse a raw object as a LyricsFile.
 * Throws a descriptive Error if the shape is invalid.
 * @param {unknown} raw
 * @returns {LyricsFile}
 */
export function parseLyricsJson(raw) {
  if (typeof raw !== 'object' || raw === null) {
    throw new Error('Lyrics JSON must be an object.');
  }
  if (!Array.isArray(raw.lyrics)) {
    throw new Error('Lyrics JSON must have a "lyrics" array.');
  }
  const lyrics = raw.lyrics.map((entry, i) => {
    if (typeof entry.time !== 'number') {
      throw new Error(`Entry ${i}: "time" must be a number (got ${JSON.stringify(entry.time)}).`);
    }
    if (typeof entry.text !== 'string') {
      throw new Error(`Entry ${i}: "text" must be a string (got ${JSON.stringify(entry.text)}).`);
    }
    return { time: entry.time, text: entry.text };
  });

  // Sort by time ascending
  lyrics.sort((a, b) => a.time - b.time);

  return { title: raw.title ?? undefined, lyrics };
}

/**
 * Load and parse a lyrics JSON File object from <input type="file">.
 * @param {File} file
 * @returns {Promise<LyricsFile>}
 */
export async function parseLyricsFile(file) {
  const text = await file.text();
  let raw;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new Error('Invalid JSON: ' + file.name);
  }
  return parseLyricsJson(raw);
}

/**
 * Get the active lyric entry for a given playback time.
 * Returns null if no entry has been reached yet.
 * @param {LyricEntry[]} lyrics
 * @param {number} currentTime
 * @returns {LyricEntry | null}
 */
export function getActiveLyric(lyrics, currentTime) {
  let active = null;
  for (const entry of lyrics) {
    if (entry.time <= currentTime) active = entry;
    else break;
  }
  return active;
}

/**
 * Build an example lyrics JSON string to show the user the expected format.
 * @returns {string}
 */
export function buildExampleLyrics() {
  const example = {
    title: 'Mi Canción',
    lyrics: [
      { time: 0.5,  text: 'Do ' },
      { time: 1.0,  text: 'Re ' },
      { time: 1.5,  text: 'Mi ' },
      { time: 2.0,  text: 'Fa ' },
      { time: 2.5,  text: 'Sol' },
    ],
  };
  return JSON.stringify(example, null, 2);
}
